robotcan_odom_node:
  ros__parameters:
    publish_rate_hz: 20.0

    tau_accel: 2.5
    tau_decel: 1.5

    velocity_scale: 0.8
    deadband: 0.02

    use_imu_yaw_rate: true

    odom_frame: "odom"
    base_frame: "base_link"

robotcan_pub_node:
  ros__parameters:
    can_port: can0
    publish_rate_hz: 20.
    wheel_base_m: 0.8
