/**:
  ros__parameters:
    device: /dev/ttyACM0
    frame_id: gps_rover

    # Retain the configuration already saved through u-center
    config_on_startup: false
    clear_bbr: false
    save_on_shutdown: false

    # Must match the rate configured in u-center
    rate: 5.0
    nav_rate: 1

    publish:
      all: false

      nav:
        all: false
        pvt: true
        relposned: true
        heading: true
        status: true
        sat: true
        cov: true

      rxm:
        all: false
        rtcm: true